### PR TITLE
Update Basque localisation

### PR DESCRIPTION
**Pull request by xabirequejo**
I've been waiting for Feditext to adapt Crowdin but it's been a year since Basque got updated and the app is not usable anymore due to the amount of strings that have been added or changed.

That is why I've tried to add the ones that were missing and fixed a few issues here and there.

Hope you don't mind.

### CODE REVIEW

**Comment by bdube** [comment]
Thank you for this update.

To be clear, does this pull request include work from Crowdin or work by other authors?

**Comment by xabirequejo** [comment]
Crowdin was used for Metatext and I was responsible for that localisation back in 2022 until the development came to a halt.

When you forked Metatext, you took the strings that I translated on Crowdin.
- So, `does this pull request include work from Crowdin?` Crowdin strings were already included, I just added (or tried to add) the strings that were missing. So I would say no.
- `does this pull request include work by other authors?` No, it doesn't. I translated Metatext on Crowdin and now I'm doing it via GitHub.

**Comment by bdube** [comment]
Thank you for the clarification. I apologize for any work that you had to do more than once.

To clarify our side of it, Feditext did not inherit the Crowdin project from Metatext. When we forked, the strings we ended up with were those that had already been committed in the Metatext repository when Metatext went into archive status. The state of the Crowdin project at the time of the fork and since then would not be reflected in the Feditext project.

With this pull request being your work, my concern about having the permission to use it goes away. Thank you.

**Comment by xabirequejo** [comment]
In that case chances are there will be errors. I submitted a few changes to Crowdin that were never adopted by Metatext (the app; not sure if the repository updated the fixed strings). We will see.

If it’s ok with you i wouldn’t mind updating the localisation from time to time, even if it’s done via PR.

**Pull request merged**
