### PR TITLE
Add czech localization

### PR DESCRIPTION
**Pull request by theokeist**
### Summary

Just add rest of the new strings

### Other Information

Not fully translated, yet

Thanks for contributing to Metatext! -->

- [ ] I have signed [Metabolist's Contributor License Agreement](https://metabolist.org/cla)
- [ ] The proposed changes are limited in scope to fixing bugs, or I have discussed larger scope changes via email

### CODE REVIEW

**Comment by OniriCorpe** [comment]
did the PR deletion was intentional @theokeist?

**Comment by theokeist** [comment]
Noooo, completly forget about this 😢

**Comment by theokeist** [comment]
I can recreate this MR during today , will be glad to do that

**Comment by theokeist** [comment]
@OniriCorpe

**Pull request closed without merging**
