### PR TITLE
Add a user preference to display rounded rectangle avatars

### PR DESCRIPTION
**Pull request by horaceyoung**
Summary

Addressing issue https://github.com/bdube/metatext/issues/78
Adding a user preference option Picker to allow users to choose between enclosing their avatars in a circle or a rounded rectangle.

#78 

Display effect:
image

### CODE REVIEW

**Comment by VyrCossont** [comment]
Instead of copy-pasting the corner radius math everywhere, what do you think about factoring out a dedicated avatar display view?

**Comment by horaceyoung** [comment]
> Instead of copy-pasting the corner radius math everywhere, what do you think about factoring out a dedicated avatar display view?

Definitely. Let me modify the code.

**Comment by horaceyoung** [comment]
> > Instead of copy-pasting the corner radius math everywhere, what do you think about factoring out a dedicated avatar display view?
> 
> Definitely. Let me modify the code.

I tried to make a new UIView but can't get it rendered somehow and lost my progress when switching branches 🥲. Maybe I need to read some other UIKit tutorials....

**Comment by VyrCossont** [comment]
@horaceyoung We need to figure out copyright assignment or licensing to deal with the GPLv3/App Store license situation before we can accept PRs, and it looks like this one is stalled out anyway, so I'm going to close this PR.

**Pull request closed without merging**
